import { TabType } from '../types';

export type ModuleCategory =
  | 'operacao'
  | 'gestao'
  | 'equipa'
  | 'financeiro'
  | 'vendas'
  | 'marketing'
  | 'inteligencia';

export interface ModuleDefinition {
  id: TabType | string;
  nameKey: string;
  descriptionKey: string;
  category: ModuleCategory;
  isEssential: boolean;
  dependencies: string[];
  iconName: string;
  defaultEnabledIn: ('INDEPENDENT' | 'SMALL_SALON' | 'CLINIC' | 'FULL_SALON' | 'FRANCHISE')[];
}

export const MODULE_CATALOG: ModuleDefinition[] = [
  // ESSENCIAIS
  {
    id: 'dashboard',
    nameKey: 'modules.dashboard.name',
    descriptionKey: 'modules.dashboard.desc',
    category: 'operacao',
    isEssential: true,
    dependencies: [],
    iconName: 'LayoutDashboard',
    defaultEnabledIn: ['INDEPENDENT', 'SMALL_SALON', 'CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'agenda',
    nameKey: 'modules.agenda.name',
    descriptionKey: 'modules.agenda.desc',
    category: 'operacao',
    isEssential: true,
    dependencies: [],
    iconName: 'Calendar',
    defaultEnabledIn: ['INDEPENDENT', 'SMALL_SALON', 'CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'clients',
    nameKey: 'modules.clients.name',
    descriptionKey: 'modules.clients.desc',
    category: 'operacao',
    isEssential: true,
    dependencies: [],
    iconName: 'Users',
    defaultEnabledIn: ['INDEPENDENT', 'SMALL_SALON', 'CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'services',
    nameKey: 'modules.services.name',
    descriptionKey: 'modules.services.desc',
    category: 'operacao',
    isEssential: true,
    dependencies: [],
    iconName: 'Sparkles',
    defaultEnabledIn: ['INDEPENDENT', 'SMALL_SALON', 'CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'caixa',
    nameKey: 'modules.caixa.name',
    descriptionKey: 'modules.caixa.desc',
    category: 'vendas',
    isEssential: true,
    dependencies: [],
    iconName: 'ShoppingBag',
    defaultEnabledIn: ['INDEPENDENT', 'SMALL_SALON', 'CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'settings',
    nameKey: 'modules.settings.name',
    descriptionKey: 'modules.settings.desc',
    category: 'operacao',
    isEssential: true,
    dependencies: [],
    iconName: 'Settings',
    defaultEnabledIn: ['INDEPENDENT', 'SMALL_SALON', 'CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },

  // OPCIONAIS / AVANÇADOS
  {
    id: 'waitlist',
    nameKey: 'modules.waitlist.name',
    descriptionKey: 'modules.waitlist.desc',
    category: 'operacao',
    isEssential: false,
    dependencies: ['agenda', 'clients'],
    iconName: 'Clock',
    defaultEnabledIn: ['SMALL_SALON', 'CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'professionals',
    nameKey: 'modules.professionals.name',
    descriptionKey: 'modules.professionals.desc',
    category: 'equipa',
    isEssential: false,
    dependencies: ['services'],
    iconName: 'UserCheck',
    defaultEnabledIn: ['SMALL_SALON', 'CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'commissions',
    nameKey: 'modules.commissions.name',
    descriptionKey: 'modules.commissions.desc',
    category: 'equipa',
    isEssential: false,
    dependencies: ['professionals', 'services'],
    iconName: 'Crown',
    defaultEnabledIn: ['SMALL_SALON', 'CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'rooms',
    nameKey: 'modules.rooms.name',
    descriptionKey: 'modules.rooms.desc',
    category: 'operacao',
    isEssential: false,
    dependencies: ['agenda'],
    iconName: 'Building2',
    defaultEnabledIn: ['CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'packages',
    nameKey: 'modules.packages.name',
    descriptionKey: 'modules.packages.desc',
    category: 'vendas',
    isEssential: false,
    dependencies: ['clients', 'services'],
    iconName: 'Gift',
    defaultEnabledIn: ['SMALL_SALON', 'CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'stock',
    nameKey: 'modules.stock.name',
    descriptionKey: 'modules.stock.desc',
    category: 'vendas',
    isEssential: false,
    dependencies: [],
    iconName: 'Package',
    defaultEnabledIn: ['CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'financial',
    nameKey: 'modules.financial.name',
    descriptionKey: 'modules.financial.desc',
    category: 'financeiro',
    isEssential: false,
    dependencies: ['caixa'],
    iconName: 'DollarSign',
    defaultEnabledIn: ['CLINIC', 'FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'marketing',
    nameKey: 'modules.marketing.name',
    descriptionKey: 'modules.marketing.desc',
    category: 'marketing',
    isEssential: false,
    dependencies: ['clients'],
    iconName: 'Megaphone',
    defaultEnabledIn: ['FULL_SALON', 'FRANCHISE'],
  },
  {
    id: 'reports',
    nameKey: 'modules.reports.name',
    descriptionKey: 'modules.reports.desc',
    category: 'inteligencia',
    isEssential: false,
    dependencies: ['caixa'],
    iconName: 'BarChart3',
    defaultEnabledIn: ['FULL_SALON', 'FRANCHISE'],
  },
];

export const PRESET_MODULES: Record<string, Record<string, boolean>> = {
  INDEPENDENT: {
    dashboard: true,
    agenda: true,
    clients: true,
    services: true,
    caixa: true,
    settings: true,
    waitlist: false,
    professionals: false,
    commissions: false,
    rooms: false,
    packages: false,
    stock: false,
    financial: false,
    marketing: false,
    reports: false,
  },
  SMALL_SALON: {
    dashboard: true,
    agenda: true,
    clients: true,
    services: true,
    caixa: true,
    settings: true,
    waitlist: true,
    professionals: true,
    commissions: true,
    rooms: false,
    packages: true,
    stock: false,
    financial: false,
    marketing: false,
    reports: false,
  },
  CLINIC: {
    dashboard: true,
    agenda: true,
    clients: true,
    services: true,
    caixa: true,
    settings: true,
    waitlist: true,
    professionals: true,
    commissions: true,
    rooms: true,
    packages: true,
    stock: true,
    financial: true,
    marketing: false,
    reports: false,
  },
  FULL_SALON: {
    dashboard: true,
    agenda: true,
    clients: true,
    services: true,
    caixa: true,
    settings: true,
    waitlist: true,
    professionals: true,
    commissions: true,
    rooms: true,
    packages: true,
    stock: true,
    financial: true,
    marketing: true,
    reports: true,
  },
  FRANCHISE: {
    dashboard: true,
    agenda: true,
    clients: true,
    services: true,
    caixa: true,
    settings: true,
    waitlist: true,
    professionals: true,
    commissions: true,
    rooms: true,
    packages: true,
    stock: true,
    financial: true,
    marketing: true,
    reports: true,
  },
};
